### ISSUE TITLE
September 2017

### ISSUE THREAD

**Issue by samerbuna** [codingdigest/codingdigest#10]

**Comment by samerbuna** [comment]
Chrome 61 has JavaScript Modules

https://developers.google.com/web/updates/2017/09/nic61

**Comment by samerbuna** [comment]
React 16 RC

https://github.com/facebook/react/issues/10294

**Comment by treyhuffine** [comment]
C++17 formally approved

**Comment by treyhuffine** [comment]
Yarn 1.0 - https://code.facebook.com/posts/274518539716230

**Comment by treyhuffine** [comment]
Vagrant 2.0 released - https://www.hashicorp.com/blog/hashicorp-vagrant-2-0/

**Comment by samerbuna** [comment]
Submlime Text 3.0 is out

https://www.sublimetext.com/blog/articles/sublime-text-3-point-0

New UI, Performance and syntax highlighting improvements, touch input support on Windows, Touch Bar support on macOS, and packaged repositories for Linux.

**Comment by samerbuna** [comment]
Nodejs 8.5 is out and it has experimental support for ES modules

https://nodejs.org/en/blog/release/v8.5.0/

**Comment by treyhuffine** [comment]
Coffee Script 2 - http://coffeescript.org/announcing-coffeescript-2/

**Comment by treyhuffine** [comment]
Swift 4 released - https://swift.org/blog/swift-4-0-released/

**Comment by treyhuffine** [comment]
Postres 10

**Comment by treyhuffine** [comment]
Java 9 release - http://jdk.java.net/9/

**Comment by samerbuna** [comment]
React relicense

https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

**Comment by treyhuffine** [comment]
It looks like React 16 is likely to come out this week.
