### ISSUE TITLE
October 2017

### ISSUE THREAD

**Issue by treyhuffine** [codingdigest/codingdigest#12]

**Comment by treyhuffine** [comment]
MongoDB IPO - https://techcrunch.com/2017/10/18/mongodb-prices-its-ipo-at-24-per-share/

**Comment by treyhuffine** [comment]
Slow month so far..

**Comment by treyhuffine** [comment]
Unreal engine 4.18 https://www.unrealengine.com/en-US/blog/unreal-engine-4-18-released

**Comment by treyhuffine** [comment]
Node 8.8.0 https://nodejs.org/en/blog/release/v8.8.0/

**Comment by samerbuna** [comment]
Goodbye Firebug 

https://hacks.mozilla.org/2017/10/saying-goodbye-to-firebug

**Comment by treyhuffine** [comment]
Android Studio 3 released - https://developer.android.com/studio/releases/index.html
