### ISSUE TITLE
November 2017

### ISSUE THREAD

**Issue by treyhuffine** [codingdigest/codingdigest#13]
Node 8 goes into LTS and Node 9.2 becomes current - https://nodejs.org/en/blog/release/v8.9.1/

**Comment by treyhuffine** [comment]
Firefox 57.0 released - https://www.mozilla.org/en-US/firefox/57.0/releasenotes/

**Comment by treyhuffine** [comment]
Web assembly supported in all major browsers - https://blog.mozilla.org/blog/2017/11/13/webassembly-in-browsers/

**Comment by samerbuna** [comment]
Security alerts on GitHub

https://github.com/blog/2470-introducing-security-alerts-on-github

**Comment by treyhuffine** [comment]
Join the battle for net neutrality - https://www.battleforthenet.com/

**Comment by treyhuffine** [comment]
React 16.2 released - https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

**Comment by treyhuffine** [comment]
Bitcoin surges past $10,000

**Comment by samerbuna** [comment]
Free Mobile App bootcamp -- https://medium.com/@samerbuna/how-about-a-free-immersive-coding-bootcamp-d8b04a2f365d

**Comment by samerbuna** [comment]
Angular 5 - https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced

**Comment by samerbuna** [comment]
Rails 5.2 Beta - http://weblog.rubyonrails.org/2017/11/27/Rails-5-2-Active-Storage-Redis-Cache-Store-HTTP2-Early-Hints-Credentials/
