### ISSUE TITLE
June 2017

### ISSUE THREAD

**Issue by treyhuffine** [codingdigest/codingdigest#7]

**Comment by samerbuna** [comment]
Prettier now supports CSS and TypeScript - https://github.com/prettier/prettier/releases/tag/1.4.0

**Comment by samerbuna** [comment]
Apple adds ad tracker blocker to desktop Safari - https://techcrunch.com/2017/06/05/apple-adds-a-tracker-blocker-to-desktop-safari/

**Comment by treyhuffine** [comment]
FreeBSD 11.1 https://lists.freebsd.org/pipermail/freebsd-stable/2017-June/087242.html

**Comment by samerbuna** [comment]
V8 version 6.0 is released: https://v8project.blogspot.com/2017/06/v8-release-60.html

**Comment by treyhuffine** [comment]
Firefox with big updates to dev tools - https://twitter.com/jasonlaster11/status/801508977486004230

May want to wait until more info comes out for this.

**Comment by treyhuffine** [comment]
Typescript 2.4 released

Dynamic imports
String ENUMs

https://blogs.msdn.microsoft.com/typescript/2017/06/27/announcing-typescript-2-4/

**Comment by treyhuffine** [comment]
React 15.6.0

**Comment by treyhuffine** [comment]
Chrome 60 beta

**Comment by samerbuna** [comment]
I think we should skip the beta/candidate releases.

**Comment by treyhuffine** [comment]
Webpack v3 released

**Comment by samerbuna** [comment]
The D Language Accepted for Inclusion in GCC

The D language offers a much cleaner syntax than C++ and now that its front-end and runtime is getting GCC support, the D language has a chance to take off. Maybe now is a good time to learn it!

Link: https://gcc.gnu.org/ml/gcc/2017-06/msg00111.html

**Comment by samerbuna** [comment]
Unicode 10 released

The Unicode encoding standard released a new version 10, which adds over 8500 new characters including 56 new emoji characters.

Link: http://unicode.org/versions/Unicode10.0.0/

**Comment by samerbuna** [comment]
GitHub release Open Source Survey 2017 - http://opensourcesurvey.org/2017/

**Comment by samerbuna** [comment]
XCode 9 and iOS 11 and ARKIT and Safari 11 (WebRTC & WebAssembly in Safari 11)

**Comment by samerbuna** [comment]
Google launches IoT service - https://techcrunch.com/2017/05/16/google-launches-cloud-service-to-manage-internet-of-things-data/

**Comment by samerbuna** [comment]
Scala updates? New version and IDE

**Comment by samerbuna** [comment]
Private fields are coming to JavaScript - Stage 2 now

**Comment by treyhuffine** [comment]
Did we discuss Node 8 in the last one or should we include that this time?

**Comment by samerbuna** [comment]
**NPX is coming to NPM**

The Node npm team recently released npx which is a tool to execute npm package binaries regardless of where they're installed. The NPM team plans to ship NPX with NPM soon.

https://github.com/nodejs/node/issues/13640

**Comment by samerbuna** [comment]
**MDN’s new design is in Beta**

The popular MDN web documentation site is getting some branding updates. The text on new black logo reads MDN web docs, mozilla, and the visual design of all MDN pages will have bolder typography and more contrast.

https://blog.mozilla.org/opendesign/mdns-new-design-beta/

**Comment by samerbuna** [comment]
**Babel and TypeScript**

A TypeScript parser for Babel was merged into the source code and it will be available for Babel version 7 which is currently in Beta. This is a good first step for TypeScript into getting major adoption in the JS community.

https://github.com/babel/babylon/releases/tag/v7.0.0-beta.16
