### ISSUE TITLE
July 2017

### ISSUE THREAD

**Issue by samerbuna** [codingdigest/codingdigest#8]

**Comment by samerbuna** [comment]
Gitter is now open-source

https://gitlab.com/gitlab-org/gitter/webapp/

**Comment by treyhuffine** [comment]
ES2017 released - https://www.ecma-international.org/publications/standards/Ecma-262.htm

**Comment by samerbuna** [comment]
npx is now packaged with npm

https://github.com/npm/npm/releases/tag/v5.2.0

**Comment by treyhuffine** [comment]
Redis 4.0 released 

https://groups.google.com/forum/#!msg/redis-db/5Kh3viziYGQ/58TKLwX0AAAJ

**Comment by treyhuffine** [comment]
Python 3.6.2 released

**Comment by treyhuffine** [comment]
Apollo Server 1.0 released

**Comment by treyhuffine** [comment]
Open Container Initiative 1.0

**Comment by treyhuffine** [comment]
^ https://coreos.com/blog/open-container-initiative-specifications-are-10

**Comment by treyhuffine** [comment]
Rust 1.19 released

**Comment by treyhuffine** [comment]
Elixir 1.5 released - https://github.com/elixir-lang/elixir/releases/tag/v1.5.0

**Comment by treyhuffine** [comment]
Flash end of life in 2020

**Comment by samerbuna** [comment]
React Fiber is Ready

Beta1 is out

http://isfiberreadyyet.com/

**Comment by treyhuffine** [comment]
very exciting
