### ISSUE TITLE
August 2017

### ISSUE THREAD

**Issue by samerbuna** [codingdigest/codingdigest#9]

**Comment by treyhuffine** [comment]
.NET Core 2.0 released - https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/

**Comment by treyhuffine** [comment]
OpenAI beats Dota 2 champions totally self taught - https://blog.openai.com/dota-2/

Slow month so adding this one. It made a lot of noise on hacker news

**Comment by samerbuna** [comment]
Bootstrap 4 beta is out

https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

**Comment by brucelane** [comment]
stensil (ionic) will support react and vuejs

**Comment by treyhuffine** [comment]
Looks like Go 1.9 will be released before the end of the month. Noting it here so that I don't forget.

**Comment by treyhuffine** [comment]
Android 8.0 (version Oreo) releaseed - https://www.android.com/versions/oreo-8-0/

**Comment by treyhuffine** [comment]
Facebook refuses to change React license after requested - https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

**Comment by samerbuna** [comment]
Node 8.4 has http2
https://nodejs.org/api/http2.html

**Comment by samerbuna** [comment]
Prettier 1.6

https://github.com/prettier/prettier/releases/tag/1.6.0

A configuration file, an ignore file, and improvements on JSX
